version: '3.9'

services:
  db:
    container_name: news-api-pgsql
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
