version: '3.9'

services:

  db:
    container_name: import-products-pgsql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    container_name: import-products-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    depends_on:
      - app
  app:
    container_name: import-products-app
    build:
      context: ./docker
      dockerfile: app.Dockerfile
    volumes:
      - ./:/var/www/app
    depends_on:
      - db

  composer:
    container_name: import-products-composer
    build:
      context: ./docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www/app
  artisan:
    container_name: import-products-artisan
    build:
      context: ./docker
      dockerfile: app.Dockerfile
    volumes:
      - ./:/var/www/app
    entrypoint: ["php", "artisan"]
